production: &production
  title: API Reference

  language_tabs: # must be one of https://git.io/vQNgJ
    - shell
    - ruby
    - python
    - javascript

  forward_includes:
    - errors

  search: true

  multiple_pages: true

  resources:
    - Kittens:'kittens'
    - Puppers:'puppers'

  kittens:
    - Get All Kittens:'get-all-kittens'
    - Get a specific kitten:'get-a-specific-kitten'
    - Delete a specific kitten:'delete-a-specific-kitten'

  puppers:
    - Get All Puppers:'get-all-puppers'
    - Get a specific pupper:'get-a-specific-pupper'
    - Delete a specific pupper:'delete-a-specific-pupper'

development:
  <<: *production
  debug: true